name: pr_test

on:
  pull_request:
    branches:
    - main

jobs:
  job1:
    name: pr_test_job1
    runs-on: ubuntu-latest

    steps:
    - name: print
      shell: bash
      run: |
        echo "finished pr triggered test"
