name: "pr_test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: add
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@nationwide.com"
          git add dist/*
          if git diff --quiet --cached dist/; then
            echo "no changes to commit"
          else
            git commit -m "add dist"
            git push -u origin ${{ github.head_ref || github.ref }}
          fi

  Pre_Test:
    name: pre_test
    needs: Build
    runs-on: [ubuntu-latest]
    steps:
      - id: clean_up
        name: clean up
        shell: bash
        run: |
          echo "pre test clean up"
