name: "workflow_test"

on:
  workflow_run:
    workflows:
      - pr_test
    types:
      - completed

jobs:
  workflow_test_job1:
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
      - name: print
        shell: bash
        run: |
          echo "finished workflow run triggered test"
