on:
  workflow_run:
    workflows:
      - pr_test
    types:
      - completed


jobs:
  job1:
    name: workflow_test_job1
    runs-on: ubuntu-latest

    steps:
    - name: print
      shell: bash
      run: |
        echo "finished workflow run triggered test"

      
