name: "workflow_test"

on:
  workflow_run:
    workflows:
      - pr_test
    types:
      - completed

jobs:
  pr_test_job1:
    runs-on: [ubuntu-latest]

    steps:
      - name: print
        shell: bash
        run: |
          echo "finished workflow run triggered test"


      
